# General Jekyll Config
pygments: true
url: https://zku.github.io/CTF
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
highlighter: pygments
# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#6A9BA1'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: zku
    twitter: skusec

  # "Hi, I'm _______"
  name: sku
  email: ochmsku@gmail.com
  tagline: "just one more flag"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: 

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false

baseurl: /CTF
